<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="(Raghav Gupta, Eli Gonzalez, Sasha S, Paul Raadnui)">

<title>Predicting Sepsis Survival Based on Clinical Records</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="sepsis-predictor-report_files/libs/clipboard/clipboard.min.js"></script>
<script src="sepsis-predictor-report_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="sepsis-predictor-report_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="sepsis-predictor-report_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="sepsis-predictor-report_files/libs/quarto-html/popper.min.js"></script>
<script src="sepsis-predictor-report_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="sepsis-predictor-report_files/libs/quarto-html/anchor.min.js"></script>
<link href="sepsis-predictor-report_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="sepsis-predictor-report_files/libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="sepsis-predictor-report_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="sepsis-predictor-report_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="sepsis-predictor-report_files/libs/bootstrap/bootstrap-1e118674f8eeaf0dc11d6faf9a2d8791.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#aim" id="toc-aim" class="nav-link active" data-scroll-target="#aim"><span class="header-section-number">1</span> Aim</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction"><span class="header-section-number">2</span> Introduction</a></li>
  <li><a href="#exploratory-data-analysis-eda" id="toc-exploratory-data-analysis-eda" class="nav-link" data-scroll-target="#exploratory-data-analysis-eda"><span class="header-section-number">3</span> Exploratory Data Analysis (EDA)</a>
  <ul class="collapse">
  <li><a href="#eda-key-findings" id="toc-eda-key-findings" class="nav-link" data-scroll-target="#eda-key-findings"><span class="header-section-number">3.1</span> EDA key findings</a></li>
  </ul></li>
  <li><a href="#model-interpretation" id="toc-model-interpretation" class="nav-link" data-scroll-target="#model-interpretation"><span class="header-section-number">4</span> Model Interpretation</a>
  <ul class="collapse">
  <li><a href="#logistic-regression-coefficients" id="toc-logistic-regression-coefficients" class="nav-link" data-scroll-target="#logistic-regression-coefficients"><span class="header-section-number">4.1</span> Logistic Regression Coefficients</a></li>
  </ul></li>
  <li><a href="#results-discussion" id="toc-results-discussion" class="nav-link" data-scroll-target="#results-discussion"><span class="header-section-number">5</span> Results &amp; Discussion</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">6</span> References</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="../sepsis-predictor-report.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Predicting Sepsis Survival Based on Clinical Records</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>(Raghav Gupta, Eli Gonzalez, Sasha S, Paul Raadnui) </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="aim" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="aim"><span class="header-section-number">1</span> Aim</h2>
<p>This project aims to explore whether basic clinical and demographic factors could be used to predict sepsis survival outcomes. Specifically, the variables Age, Sex, and Sepsis Episode Number were examined to determine their influence on a patient’s probability of survival after hospitalization.</p>
<p>A dataset of over 110,000 hospital admissions from Norway (2011–2012) was obtained from the UCI Sepsis Survival Minimal Clinical Records repository <span class="citation" data-cites="chicco2020sepsisdataset">(<a href="#ref-chicco2020sepsisdataset" role="doc-biblioref">Chicco and Jurman 2020</a>)</span>. After the Exploratory Data Analysis, a Logistic Regression model was trained and tuned via randomized search with cross-validation. Model performance was evaluated using standard metrics, including ROC AUC, Precision, Recall, and F1-score, and further interpreted using SHAP (SHapley Additive exPlanations) values to assess feature importance and contribution.</p>
<p>The results showed that the model achieved a ROC AUC of 0.588, with high recall but limited discriminative power. Age emerged as the strongest predictor of survival: as you get older your probability of survival decreases, with SHAP values confirming its dominant influence on the model’s output. In contrast, Sex and Episode Number had minimal impact on predictions. These findings suggest that while demographic factors provide limited predictive ability on their own, Age remains a crucial indicator of mortality risk in sepsis patients.</p>
<p>The analysis highlights the need for more clinical features to improve model accuracy, showing that Age and Gender are not good predictors for survival probabilities.</p>
</section>
<section id="introduction" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="introduction"><span class="header-section-number">2</span> Introduction</h2>
<p>Sepsis is a life-threatening condition that occurs when the immune system overreacts to an infection causing organ dysfunction <span class="citation" data-cites="clevelandclinic2022septicshock">(<a href="#ref-clevelandclinic2022septicshock" role="doc-biblioref">Clinic 2022</a>)</span>. The reaction can cause damage to tissues and organs and it can lead to severe sepsis from low blood pressure as a result of inflammation throughout the body. The last stage is septic shock which is when blood pressure is so low that it cannot supply enough blood to vital organs such as the brain, kidneys, and liver, causing them to fail and possibly leading to death. Generally, sepsis is usually caused by bacterial infections but it could be from parasites, viruses, and fungi infections in the bloodstream, lungs. and urinary tract <span class="citation" data-cites="who2024sepsis">(<a href="#ref-who2024sepsis" role="doc-biblioref">Organization 2024</a>)</span>. Common symptoms for sepsis include fever, fast heart rate, rapid breathing, low blood pressure, confusion, skin rash, chills and shivering, etc <span class="citation" data-cites="canadiancancer2024septicshock">(<a href="#ref-canadiancancer2024septicshock" role="doc-biblioref">Society 2024</a>)</span>.</p>
<p>Since sepsis requires urgent medical care, a machine learning algorithm that can be used to predict if a patient is likely to survive or pass away after being hospitalized for a specific time interval from septic shock is crucial. Sepsis is often associated with immediate death risk and it can kill patients as fast as within an hour if not treated promptly. An accurate and fast machine learning model will help medical staff prioritize patients who need more urgent care and possibly save more patients from this life-threatening condition. Also, this study aims to identify which factor contributes to whether a patient is more likely to be dead from sepsis. Therefore, if a machine learning algorithm can promptly and accurately classify patients, this could lead to a better sepsis patient prioritization and save more lives.</p>
<p>To answer this question and produce a machine learning model, the datasets of 110,204 admissions of 84,811 hospitalized subjects between 2011 and 2012 in Norway who were diagnosed with infections, systemic inflammatory response syndrome, sepsis by causative microbes, or septic shock will be utilized to analyze and build a machine learning algorithm. It was sourced from the UCI Machine Learning Repository <span class="citation" data-cites="chicco2020sepsisdataset">(<a href="#ref-chicco2020sepsisdataset" role="doc-biblioref">Chicco and Jurman 2020</a>)</span>. Each row in the data set represents each patient information including their age, sex, and number of prior sepsis episodes. There is an outcome of each patient whether they survive at a time of about 9 days after being hospitalized in each row. All the patients’ admissions are only defined by the novel Sepsis-3 definition.</p>
</section>
<section id="exploratory-data-analysis-eda" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="exploratory-data-analysis-eda"><span class="header-section-number">3</span> Exploratory Data Analysis (EDA)</h2>
<p>EDA is conducted first to see if any data wrangling is needed before proceeding to building a machine learning model.</p>
<p>From the current train and test datasets, all the data are already clean. Age ranges from 0–100 years, Sex is encoded as male/female, and Episode Number varies between 1–5 with no missing values, so no imputation is required.</p>
<div id="fig-univariate" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-univariate-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../results/figures/univariate_visualization.png" class="img-fluid figure-img" style="width:105.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-univariate-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Age, Episode Count &amp; Sex Distribution
</figcaption>
</figure>
</div>
<p><a href="#fig-univariate" class="quarto-xref">Figure&nbsp;1</a> presents three univariate visualizations that provide an initial understanding of feature distributions and how they relate to survival outcome:</p>
<ul>
<li><strong>Age distribution:</strong> The left histogram shows age is widely spread between 0–100 years, with a clear right-skew toward older patients. Both survival and death outcomes overlap heavily across ages, but deaths appear slightly more common in the upper age range.</li>
<li><strong>Episode count distribution:</strong> The middle bar chart reveals that most patients experience only a single prior sepsis episode, with rapidly decreasing frequency as episode count increases.</li>
<li><strong>Sex vs Outcome counts:</strong> The heatmap on the right displays the cross-tabulation of sex and survival outcome. Both males and females predominantly fall under the <em>survived</em> category, with similar proportions, indicating sex alone is not a strong differentiator for survival.</li>
</ul>
<div id="fig-multivariate" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-multivariate-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../results/figures/multivariate_visualization.png" class="img-fluid figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-multivariate-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Relationship of Features with Outcome
</figcaption>
</figure>
</div>
<p><a href="#fig-multivariate" class="quarto-xref">Figure&nbsp;2</a> presents multivariate distributions using boxplots, showing how age varies with episode count and patient sex across outcome groups.</p>
<div id="fig-corr" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-corr-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../results/figures/correlation_heatmap.png" class="img-fluid figure-img" style="width:70.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-corr-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Feature Correlation Heatmap
</figcaption>
</figure>
</div>
<p><a href="#fig-corr" class="quarto-xref">Figure&nbsp;3</a> displays the correlation heatmap, confirming that age is the most strongly related feature to survival outcome, while sex and episode count show weaker associations.</p>
<section id="eda-key-findings" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="eda-key-findings"><span class="header-section-number">3.1</span> EDA key findings</h3>
<p><a href="#fig-univariate" class="quarto-xref">Figure&nbsp;1</a> illustrates the age distribution and outcome imbalance.</p>
<p>As seen in <a href="#fig-multivariate" class="quarto-xref">Figure&nbsp;2</a>, age varies across outcome and episode groups.</p>
<p><a href="#fig-corr" class="quarto-xref">Figure&nbsp;3</a> confirms age as the strongest predictor for survival.</p>
<ul>
<li><strong>Highly imbalanced target</strong>: The dataset contains a majority of Sepsis survivors (93%). This suggests the use of specific metrics (e.g., recall, precision, aucpr) and resampling techniques to address class imbalance.</li>
<li><strong>Weak predictors</strong>: Correlation analysis and visualizations showed that there are no strong associations between any of the features and the target. This suggests that these features might have limited predictive power and the model may not be able to generalize well with such features</li>
<li><strong>No Multicolinearity</strong>: No high correlation between features, so no risk of multicolinearity.</li>
<li><strong>What preprocessing needs to be applied</strong>:
<ul>
<li><em>Age</em> is a numeric variable and should be standardized, no missing values.</li>
<li><em>Sex</em> is a binary categorical variable with no order of magnitude and should be one-hot encoded, no missing values.</li>
<li><em>Episode number</em> is a numeric variable and should be standardized, no missing values.</li>
</ul></li>
</ul>
<div class="cell" data-execution_count="2">
<div id="tbl-metrics" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="2">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-metrics-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Logistic Regression performance on train/test sets.
</figcaption>
<div aria-describedby="tbl-metrics-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="2">
<div>


<table class="dataframe do-not-create-environment cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">dataset</th>
<th data-quarto-table-cell-role="th">roc auc</th>
<th data-quarto-table-cell-role="th">precision</th>
<th data-quarto-table-cell-role="th">recall</th>
<th data-quarto-table-cell-role="th">F1 score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>train</td>
<td>0.70589</td>
<td>0.926455</td>
<td>1.0</td>
<td>0.961823</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>test</td>
<td>0.58812</td>
<td>0.810719</td>
<td>1.0</td>
<td>0.895466</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
<p>By looking at the classification metrics above we can directly see that the model achieved a train ROC AUC of 0.706 and a test ROC AUC of 0.588. This is likely due to the very limited number of features available to train the model, which limits its ability to generalize well to unseen data and the data imbalance between target groups.</p>
<p>As seen in <a href="#fig-univariate" class="quarto-xref">Figure&nbsp;1</a>, the predicted probability distributions for Survived and Died overlap almost completely.<br>
This explains the weak ROC AUC: the model struggles to rank classes effectively given the limited features available.<br>
<a href="#tbl-metrics" class="quarto-xref">Table&nbsp;1</a> confirms that recall and precision are inflated due to class imbalance, and the model overfits by performing much better on training data than test data.</p>
</section>
</section>
<section id="model-interpretation" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="model-interpretation"><span class="header-section-number">4</span> Model Interpretation</h2>
<section id="logistic-regression-coefficients" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="logistic-regression-coefficients"><span class="header-section-number">4.1</span> Logistic Regression Coefficients</h3>
<p>The final logistic model learned the relationship between features and survival:</p>
<p>logit(p) = 2.993 -1.069·Age -0.018·Episode Number -0.178·Is Male</p>
<p>Even though the model underperforms, we can still interpret the learned coefficients:</p>
<ul>
<li>The intercept is <strong>2.993</strong>, representing baseline survival log-odds when all predictors equal zero.</li>
<li><strong>Age has the strongest negative effect (-1.069)</strong>, meaning survival probability decreases as age increases.</li>
<li><strong>Episode number has a small coefficient (-0.018)</strong>, suggesting only minor influence on survival.</li>
<li><strong>Being male has a coefficient of (-0.178)</strong>, indicating slightly lower survival odds than females.</li>
</ul>
<section id="shap-explanation-and-feature-importance" class="level4" data-number="4.1.1">
<h4 data-number="4.1.1" class="anchored" data-anchor-id="shap-explanation-and-feature-importance"><span class="header-section-number">4.1.1</span> SHAP Explanation and Feature Importance</h4>
<p>[<strong>SHAP</strong> <em>(SHapley Additive exPlanations)</em>] <span class="citation" data-cites="lundberg2025shap">(<a href="#ref-lundberg2025shap" role="doc-biblioref">Lundberg, Lee, and contributors 2025</a>)</span> is a method used to explain how individual features contribute to a machine learning model’s predictions. It assigns a numerical value to each feature that represents how much that feature pushes the prediction up or down. A higher SHAP value indicates a higher level of importance, meaning the feature has a stronger influence on the model’s decision. SHAP is particularly useful for understanding both global feature importance and how a single observation is being predicted. In this analysis, SHAP values are used to determine which features are most important in the logistic regression model predicting sepsis hospital survival.</p>
<p>To interpret the logistic regression model, SHAP values were computed to measure the contribution of each feature to the model’s output. The model includes three predictors: age_in_years, sex, and episode_number. The SHAP values represent the average magnitude by which each feature affects the prediction across all test samples.</p>
<p>The SHAP summary plot below visualizes how each feature contributes to the logistic regression model’s output. The longest bar corresponds to the feature with the highest average absolute SHAP impact — meaning it contributes the most to shifting predictions up or down.</p>
<div id="fig-shap" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-shap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../results/figures/shap_values_plot.png" class="img-fluid figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-shap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: SHAP Feature Importance Summary
</figcaption>
</figure>
</div>
<p>From the plot, <strong>Age is clearly the most influential feature</strong>, showing the largest magnitude of SHAP values. This means that changes in age have the strongest effect on predicted survival probability. <strong>Episode number</strong> has noticeably lower impact, while <strong><code>is_male</code> (encoded from Sex) contributes very little to the model</strong>, indicating minimal difference in predicted survival between males and females.</p>
<p>These observations align with earlier findings from the coefficients and correlation analysis — the model relies primarily on age when predicting survival, while the other two variables provide limited predictive signal.</p>
<p>Overall, the SHAP analysis shows that age is the dominant predictor used by the model, and that there’s a negative association between age and survival probability. Sex has minimal influence, but it suggests also that males have a slightly smaller chance to survive to a Sepsis episode.</p>
</section>
</section>
</section>
<section id="results-discussion" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="results-discussion"><span class="header-section-number">5</span> Results &amp; Discussion</h2>
<p>The results of the analysis indicate that age is the dominant factor influencing survival in sepsis patients. Both the correlation analysis and SHAP explainability results show that older patients have a significantly lower probability of survival, with age having a mean SHAP importance value nearly ten times higher than any other feature. In contrast, sex and episode number contribute minimally, suggesting that demographic features alone cannot capture the full complexity of sepsis mortality risk.</p>
<p>The model achieved a test ROC AUC of 0.588, indicating limited discriminative ability.<br>
Despite a high recall of 1.000 and a precision of 0.811 on the test set, these inflated values are largely driven by the strong class imbalance (approximately 93% survivors vs 7% non-survivors).</p>
</section>
<section id="references" class="level2 unnumbered" data-number="6">


</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">6 References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-chicco2020sepsisdataset" class="csl-entry" role="listitem">
Chicco, Davide, and Giovanni Jurman. 2020. <span>“Sepsis Survival Minimal Clinical Records [Dataset].”</span> UCI Machine Learning Repository. <a href="https://doi.org/10.24432/C53C8N">https://doi.org/10.24432/C53C8N</a>.
</div>
<div id="ref-clevelandclinic2022septicshock" class="csl-entry" role="listitem">
Clinic, Cleveland. 2022. <span>“Septic Shock: Causes, Symptoms &amp; Treatment.”</span> <a href="https://my.clevelandclinic.org/health/diseases/23255-septic-shock">https://my.clevelandclinic.org/health/diseases/23255-septic-shock</a>.
</div>
<div id="ref-lundberg2025shap" class="csl-entry" role="listitem">
Lundberg, Scott M., Su-In Lee, and SHAP contributors. 2025. <span>“SHAP (SHapley Additive exPlanations) [Computer Software].”</span> <a href="https://github.com/shap/shap">https://github.com/shap/shap</a>.
</div>
<div id="ref-who2024sepsis" class="csl-entry" role="listitem">
Organization, World Health. 2024. <span>“Sepsis.”</span> <a href="https://www.who.int/news-room/fact-sheets/detail/sepsis">https://www.who.int/news-room/fact-sheets/detail/sepsis</a>.
</div>
<div id="ref-canadiancancer2024septicshock" class="csl-entry" role="listitem">
Society, Canadian Cancer. 2024. <span>“Sepsis and Septic Shock.”</span> <a href="https://cancer.ca/en/treatments/side-effects/septic-shock">https://cancer.ca/en/treatments/side-effects/septic-shock</a>.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>